# Generated by Django 5.2.12 on 2026-04-18 17:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_userotp'),
        ('otp_totp', '0003_add_timestamps'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminTOTPDevice',
            fields=[
                ('totpdevice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='otp_totp.totpdevice')),
            ],
            options={
                'verbose_name': 'Admin TOTP Device',
                'verbose_name_plural': 'Admin TOTP Devices',
            },
            bases=('otp_totp.totpdevice',),
        ),
        migrations.CreateModel(
            name='AdminBackupCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('is_used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_backup_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admin Backup Code',
                'verbose_name_plural': 'Admin Backup Codes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdminSecurityQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(choices=[('mother_maiden', "What is your mother's maiden name?"), ('first_pet', 'What was the name of your first pet?'), ('birth_city', 'In what city were you born?'), ('first_school', 'What was the name of your first school?'), ('favorite_teacher', 'Who was your favorite teacher?')], max_length=50)),
                ('answer', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security_questions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admin Security Question',
                'verbose_name_plural': 'Admin Security Questions',
                'unique_together': {('user', 'question')},
            },
        ),
    ]
